# Config

ins_ros_node:
  ros__parameters:

    # ============================================================
    # General
    # ============================================================
    frames:
      world: odom
      body: ona2/imu_front

    tf:
      publish: true

    # ============================================================
    # Filter
    # ============================================================
    filter:
      type: iESEKF

      iterations:
        max: 5
        tolerance: 1.e-5

      process_noise:
        gyro: 0.015
        accel: 0.15
        gyro_bias: 1.54e-5
        accel_bias: 3.38e-4

    # ============================================================
    # Sensors
    # ============================================================
    sensors:

      imu:
        type: imu
        enabled: true

        topic: /ona2/sensors/imu_front/imu_uncalib

      gps:
        type: gps
        enabled: true

        topic: /fix

        covariance:
          position: 1.0
          velocity: 0.1

        lever_arm:
          x: -0.4
          y: 0.0
          z: 0.5

      pose:
        type: pose
        enabled: false

        topic: /input/pose

      wheel_odom:
        type: wheel_odom
        enabled: false

        topic: /input/wheel_odom

      baro:
        type: barometer
        enabled: false

        topic: /input/baro

        covariance:
          altitude: 2.0

      mag:
        type: magnetometer
        enabled: false

        topic: /input/mag